export const MOCK_USERS: MUser.IRecord[] = [
  {
    userId: "USR-001",
    fullName: "Nguyễn Văn An",
    nameAscii: "Nguyen Van An",
    gender: "Nam",
    dob: "1980-05-14",
    nationalId: "001080012345",
    orcid: "0000-0002-1234-5678",
    externalIds: {
      scopusAuthorId: "57200000001",
      wosResearcherId: "AAA-0001-2020",
      googleScholarId: "abcDEF1234",
    },
    affiliationPrimary: "Trường Đại học Bách Khoa Hà Nội",
    departments: [
      { name: "Khoa Điện tử Viễn thông", role: "Trưởng khoa" },
      { name: "Trung tâm Nghiên cứu AI", role: "Thành viên" },
    ],
    academicRankCurrent: "Phó Giáo sư",
    degreeHighest: "Tiến sĩ",
    politicalTheoryStatus: "Cao cấp",
    foreignLanguageCerts: [
      {
        type: "IELTS",
        score: "7.0",
        issuedDate: "2021-03-10",
        issuedBy: "British Council",
      },
    ],
  },
  {
    userId: "USR-002",
    fullName: "Trần Thị Bích",
    nameAscii: "Tran Thi Bich",
    gender: "Nữ",
    dob: "1988-11-20",
    nationalId: "001088056789",
    orcid: "0000-0002-8765-4321",
    externalIds: {
      scopusAuthorId: "57200000002",
      googleScholarId: "xyZABC5678",
    },
    affiliationPrimary: "Trường Đại học Khoa học Tự nhiên – ĐHQGHN",
    departments: [{ name: "Khoa Toán – Cơ – Tin học" }],
    academicRankCurrent: "Giảng viên chính",
    degreeHighest: "Tiến sĩ",
    politicalTheoryStatus: "Trung cấp",
    foreignLanguageCerts: [
      {
        type: "TOEFL iBT",
        score: "95",
        issuedDate: "2022-06-15",
        issuedBy: "ETS",
      },
    ],
  },
  {
    userId: "USR-003",
    fullName: "Lê Minh Tuấn",
    nameAscii: "Le Minh Tuan",
    gender: "Nam",
    dob: "1975-02-28",
    nationalId: "001075098765",
    orcid: "0000-0001-9876-5432",
    externalIds: {
      scopusAuthorId: "57200000003",
      wosResearcherId: "BBB-0002-2019",
    },
    affiliationPrimary: "Viện Khoa học và Công nghệ Việt Nam",
    departments: [{ name: "Viện Công nghệ Thông tin", role: "Phó Viện trưởng" }],
    academicRankCurrent: "Giáo sư",
    degreeHighest: "Tiến sĩ Khoa học",
    politicalTheoryStatus: "Cao cấp",
    foreignLanguageCerts: [
      {
        type: "Tiếng Anh",
        score: "C1",
        issuedDate: "2019-09-01",
        issuedBy: "Cambridge Assessment",
      },
    ],
  },
];