export const MOCK_DEGREES: MDegree.IRecord[] = [
  {
    degreeId: "DEG-001",
    userId: "USR-001",
    level: "Cử nhân",
    major: "Kỹ thuật Điện tử",
    institution: "Trường Đại học Bách Khoa Hà Nội",
    country: "Việt Nam",
    graduationDate: "2002-06-30",
  },
  {
    degreeId: "DEG-002",
    userId: "USR-001",
    level: "Tiến sĩ",
    thesisTitle:
      "Nghiên cứu phương pháp học sâu trong nhận dạng tiếng nói tiếng Việt",
    major: "Kỹ thuật Điện tử – Viễn thông",
    institution: "Université de Grenoble Alpes",
    country: "Pháp",
    graduationDate: "2008-11-15",
    diplomaFileId: "FILE-001",
  },
  {
    degreeId: "DEG-003",
    userId: "USR-002",
    level: "Cử nhân",
    major: "Toán học",
    institution: "Trường Đại học Khoa học Tự nhiên – ĐHQGHN",
    country: "Việt Nam",
    graduationDate: "2010-06-20",
  },
  {
    degreeId: "DEG-004",
    userId: "USR-002",
    level: "Thạc sĩ",
    thesisTitle: "Giải thuật tối ưu cho bài toán lập lịch đa mục tiêu",
    major: "Khoa học Máy tính",
    institution: "Trường Đại học Khoa học Tự nhiên – ĐHQGHN",
    country: "Việt Nam",
    graduationDate: "2012-12-10",
    diplomaFileId: "FILE-005",
  },
  {
    degreeId: "DEG-005",
    userId: "USR-002",
    level: "Tiến sĩ",
    thesisTitle: "Deep Reinforcement Learning for Combinatorial Optimization",
    major: "Khoa học Máy tính",
    institution: "National University of Singapore",
    country: "Singapore",
    graduationDate: "2017-05-30",
    diplomaFileId: "FILE-005",
  },
  {
    degreeId: "DEG-006",
    userId: "USR-003",
    level: "Tiến sĩ",
    thesisTitle: "Mô hình ngôn ngữ thống kê cho tiếng Việt",
    major: "Tin học",
    institution: "Trường Đại học Tổng hợp Hà Nội",
    country: "Việt Nam",
    graduationDate: "2001-04-25",
  },
  {
    degreeId: "DEG-007",
    userId: "USR-003",
    level: "Tiến sĩ Khoa học",
    thesisTitle: "Xử lý ngôn ngữ tự nhiên và ứng dụng trong hệ thống thông minh",
    major: "Tin học",
    institution: "Viện Hàn lâm Khoa học Nga",
    country: "Nga",
    graduationDate: "2007-10-18",
  },
];