export const MOCK_TEACHING: MTeaching.IRecord[] = [
  {
    teachId: "TCH-001",
    userId: "USR-001",
    academicYear: "2023-2024",
    semester: "HK1",
    courseCode: "ET3280",
    courseName: "Xử lý Tiếng nói",
    credits: 3,
    role: "Chính",
    hoursEquiv: 60,
    evaluationScore: 4.5,
  },
  {
    teachId: "TCH-002",
    userId: "USR-001",
    academicYear: "2023-2024",
    semester: "HK1",
    courseCode: "ET4520",
    courseName: "Học sâu nâng cao",
    credits: 3,
    role: "Chính",
    hoursEquiv: 60,
    evaluationScore: 4.7,
  },
  {
    teachId: "TCH-003",
    userId: "USR-001",
    academicYear: "2022-2023",
    semester: "HK2",
    courseCode: "ET3281",
    courseName: "Nhận dạng mẫu",
    credits: 3,
    role: "Chính",
    hoursEquiv: 60,
    evaluationScore: 4.4,
  },
  {
    teachId: "TCH-004",
    userId: "USR-002",
    academicYear: "2023-2024",
    semester: "HK1",
    courseCode: "MTH3201",
    courseName: "Toán rời rạc",
    credits: 4,
    role: "Chính",
    hoursEquiv: 75,
    evaluationScore: 4.6,
  },
  {
    teachId: "TCH-005",
    userId: "USR-002",
    academicYear: "2023-2024",
    semester: "HK2",
    courseCode: "CS4210",
    courseName: "Thuật toán tối ưu hóa",
    credits: 3,
    role: "Chính",
    hoursEquiv: 60,
    evaluationScore: 4.8,
  },
  {
    teachId: "TCH-006",
    userId: "USR-003",
    academicYear: "2023-2024",
    semester: "HK1",
    courseCode: "CS5100",
    courseName: "Xử lý Ngôn ngữ Tự nhiên",
    credits: 3,
    role: "Chính",
    hoursEquiv: 60,
    evaluationScore: 4.9,
  },
];