export const MOCK_SUPERVISION: MSupervision.IRecord[] = [
  {
    supId: "SUP-001",
    userId: "USR-001",
    level: "Tiến sĩ",
    studentName: "Lê Văn Cường",
    institution: "Trường Đại học Bách Khoa Hà Nội",
    thesisTitle:
      "Mô hình ngôn ngữ lớn cho nhận dạng thực thể có tên trong văn bản y tế tiếng Việt",
    startDate: "2021-09-01",
    status: "Đang làm",
    decisionFileId: "FILE-008",
    role: "Hướng dẫn chính",
  },
  {
    supId: "SUP-002",
    userId: "USR-001",
    level: "Tiến sĩ",
    studentName: "Hoàng Thị Mai",
    institution: "Trường Đại học Bách Khoa Hà Nội",
    thesisTitle: "Speech Emotion Recognition Using Multimodal Deep Learning",
    startDate: "2020-09-01",
    defenseDate: "2023-11-20",
    status: "Đã bảo vệ",
    decisionFileId: "FILE-008",
    role: "Đồng hướng dẫn",
  },
  {
    supId: "SUP-003",
    userId: "USR-001",
    level: "Thạc sĩ",
    studentName: "Vũ Đức Dũng",
    institution: "Trường Đại học Bách Khoa Hà Nội",
    thesisTitle: "Ứng dụng BERT cho phân tích cảm xúc tiếng Việt trên mạng xã hội",
    startDate: "2022-09-01",
    defenseDate: "2023-06-15",
    status: "Đã bảo vệ",
    role: "Hướng dẫn chính",
  },
  {
    supId: "SUP-004",
    userId: "USR-002",
    level: "Tiến sĩ",
    studentName: "Ngô Thanh Hải",
    institution: "Trường Đại học Khoa học Tự nhiên – ĐHQGHN",
    thesisTitle:
      "Hybrid Deep Learning Algorithms for Supply Chain Optimization",
    startDate: "2022-09-01",
    status: "Đang làm",
    role: "Đồng hướng dẫn",
  },
  {
    supId: "SUP-005",
    userId: "USR-002",
    level: "Thạc sĩ",
    studentName: "Đinh Thị Hương",
    institution: "Trường Đại học Khoa học Tự nhiên – ĐHQGHN",
    thesisTitle: "Giải thuật học tăng cường cho bài toán sắp xếp kho hàng",
    startDate: "2023-09-01",
    status: "Đang làm",
    role: "Hướng dẫn chính",
  },
  {
    supId: "SUP-006",
    userId: "USR-003",
    level: "Tiến sĩ",
    studentName: "Phan Văn Khoa",
    institution: "Viện Công nghệ Thông tin – VAST",
    thesisTitle:
      "Hệ thống hỏi đáp tự động dựa trên tri thức cho tiếng Việt",
    startDate: "2019-01-01",
    defenseDate: "2022-05-10",
    status: "Đã bảo vệ",
    role: "Đồng hướng dẫn",
  },
];