export const MOCK_POSITION_HISTORY: MPositionHistory.IRecord[] = [
  {
    positionId: "POS-001",
    userId: "USR-001",
    title: "Giảng viên",
    unit: "Khoa Điện tử Viễn thông – ĐH Bách Khoa HN",
    startDate: "2005-09-01",
    endDate: "2015-08-31",
  },
  {
    positionId: "POS-002",
    userId: "USR-001",
    title: "Phó Trưởng khoa",
    unit: "Khoa Điện tử Viễn thông – ĐH Bách Khoa HN",
    startDate: "2015-09-01",
    endDate: "2021-08-31",
    decisionFileId: "FILE-002",
  },
  {
    positionId: "POS-003",
    userId: "USR-001",
    title: "Trưởng khoa",
    unit: "Khoa Điện tử Viễn thông – ĐH Bách Khoa HN",
    startDate: "2021-09-01",
    decisionFileId: "FILE-002",
  },
  {
    positionId: "POS-004",
    userId: "USR-002",
    title: "Giảng viên",
    unit: "Khoa Toán – Cơ – Tin học – ĐHKHTN",
    startDate: "2013-10-01",
    endDate: "2020-09-30",
  },
  {
    positionId: "POS-005",
    userId: "USR-002",
    title: "Giảng viên chính",
    unit: "Khoa Toán – Cơ – Tin học – ĐHKHTN",
    startDate: "2020-10-01",
  },
  {
    positionId: "POS-006",
    userId: "USR-003",
    title: "Nghiên cứu viên",
    unit: "Viện Công nghệ Thông tin – VAST",
    startDate: "2002-01-01",
    endDate: "2010-12-31",
  },
  {
    positionId: "POS-007",
    userId: "USR-003",
    title: "Phó Viện trưởng",
    unit: "Viện Công nghệ Thông tin – VAST",
    startDate: "2011-01-01",
  },
];