export const MOCK_EVIDENCE_FILES: MEvidenceFile.IRecord[] = [
  {
    fileId: "FILE-001",
    ownerUserId: "USR-001",
    fileName: "bang_tien_si_nguyen_van_an.pdf",
    fileType: "application/pdf",
    source: "Tải lên",
    url: "https://storage.example.com/files/FILE-001.pdf",
    accessScope: "Hội đồng",
  },
  {
    fileId: "FILE-002",
    ownerUserId: "USR-001",
    fileName: "quyet_dinh_bo_nhiem_truong_khoa_2021.pdf",
    fileType: "application/pdf",
    source: "Nội bộ",
    url: "https://storage.example.com/files/FILE-002.pdf",
    accessScope: "Hội đồng",
  },
  {
    fileId: "FILE-003",
    ownerUserId: "USR-001",
    fileName: "bai_bao_scopus_2022_firstpage.pdf",
    fileType: "application/pdf",
    source: "Tải lên",
    url: "https://storage.example.com/files/FILE-003.pdf",
    accessScope: "Công khai",
  },
  {
    fileId: "FILE-004",
    ownerUserId: "USR-001",
    fileName: "de_tai_nafosted_2020_quyet_dinh.pdf",
    fileType: "application/pdf",
    source: "Tải lên",
    url: "https://storage.example.com/files/FILE-004.pdf",
    accessScope: "Hội đồng",
  },
  {
    fileId: "FILE-005",
    ownerUserId: "USR-002",
    fileName: "bang_thac_si_tran_thi_bich.pdf",
    fileType: "application/pdf",
    source: "Tải lên",
    url: "https://storage.example.com/files/FILE-005.pdf",
    accessScope: "Hội đồng",
  },
  {
    fileId: "FILE-006",
    ownerUserId: "USR-002",
    fileName: "ielts_cert_tran_thi_bich_2023.pdf",
    fileType: "application/pdf",
    source: "Tải lên",
    url: "https://storage.example.com/files/FILE-006.pdf",
    accessScope: "Riêng tư",
  },
  {
    fileId: "FILE-007",
    ownerUserId: "USR-001",
    fileName: "giai_thuong_nha_khoa_hoc_tre_2022.pdf",
    fileType: "application/pdf",
    source: "Tải lên",
    url: "https://storage.example.com/files/FILE-007.pdf",
    accessScope: "Công khai",
  },
  {
    fileId: "FILE-008",
    ownerUserId: "USR-001",
    fileName: "bien_ban_huong_dan_ncs_le_van_cuong.pdf",
    fileType: "application/pdf",
    source: "Nội bộ",
    url: "https://storage.example.com/files/FILE-008.pdf",
    accessScope: "Hội đồng",
  },
];