export const MOCK_PUBLICATIONS: MPublication.IRecord[] = [
  {
    pubId: "PUB-001",
    userId: "USR-001",
    type: "journal_article",
    title:
      "End-to-End Speech Recognition for Vietnamese Using Conformer with Data Augmentation",
    authors: [
      { fullName: "Nguyễn Văn An", order: 1, role: "first" },
      { fullName: "Trần Thị Bích", order: 2, role: "co" },
      { fullName: "John Smith", order: 3, role: "corresponding" },
    ],
    year: 2022,
    publicationDate: "2022-07-15",
    journalTitle: "IEEE/ACM Transactions on Audio, Speech, and Language Processing",
    issn: "2329-9290",
    eIssn: "2329-9304",
    volume: "30",
    pages: "2105-2118",
    doi: "10.1109/TASLP.2022.3183456",
    indexing: ["Scopus", "WOS"],
    quartile: "Q1",
    citationCount: 47,
    selfCitationCount: 3,
    hdgsPointYear: 2,
    evidenceFileId: "FILE-003",
  },
  {
    pubId: "PUB-002",
    userId: "USR-001",
    type: "conference_paper",
    title:
      "Vietnamese Named Entity Recognition Using BERT-based Multilingual Model",
    authors: [
      { fullName: "Nguyễn Văn An", order: 1, role: "first" },
      { fullName: "Phạm Quốc Hùng", order: 2, role: "co" },
    ],
    year: 2021,
    publicationDate: "2021-11-10",
    proceedingsTitle:
      "Proceedings of the 2021 Conference on Empirical Methods in Natural Language Processing",
    isbn: "978-1-954085-88-9",
    pages: "3201-3210",
    doi: "10.18653/v1/2021.emnlp-main.256",
    indexing: ["Scopus"],
    quartile: "Q2",
    citationCount: 22,
    hdgsPointYear: 1,
    evidenceFileId: "FILE-003",
  },
  {
    pubId: "PUB-003",
    userId: "USR-002",
    type: "journal_article",
    title:
      "A Hybrid Metaheuristic for Multi-Objective Job Shop Scheduling with Energy Constraints",
    authors: [
      { fullName: "Trần Thị Bích", order: 1, role: "first" },
      { fullName: "Lê Minh Tuấn", order: 2, role: "co" },
    ],
    year: 2023,
    publicationDate: "2023-02-20",
    journalTitle: "Computers & Operations Research",
    issn: "0305-0548",
    volume: "151",
    pages: "106087",
    doi: "10.1016/j.cor.2022.106087",
    indexing: ["Scopus", "WOS"],
    quartile: "Q1",
    citationCount: 18,
    selfCitationCount: 1,
    hdgsPointYear: 2,
  },
  {
    pubId: "PUB-004",
    userId: "USR-003",
    type: "book",
    title: "Xử lý Ngôn ngữ Tự nhiên: Lý thuyết và Ứng dụng",
    authors: [{ fullName: "Lê Minh Tuấn", order: 1, role: "first" }],
    year: 2020,
    journalTitle: "Nhà xuất bản Khoa học và Kỹ thuật",
    isbn: "978-604-67-1234-5",
    hdgsPointYear: 3,
  },
  {
    pubId: "PUB-005",
    userId: "USR-002",
    type: "journal_article",
    title:
      "Solving Vehicle Routing Problems with Time Windows Using Deep Q-Network",
    authors: [
      { fullName: "Trần Thị Bích", order: 1, role: "corresponding" },
      { fullName: "Nguyễn Phương Linh", order: 2, role: "co" },
      { fullName: "Lê Minh Tuấn", order: 3, role: "co" },
    ],
    year: 2022,
    journalTitle: "Applied Soft Computing",
    issn: "1568-4946",
    volume: "127",
    pages: "109370",
    doi: "10.1016/j.asoc.2022.109370",
    indexing: ["Scopus", "WOS"],
    quartile: "Q1",
    citationCount: 35,
    selfCitationCount: 2,
    hdgsPointYear: 2,
  },
];